import styled from 'styled-components';

const Data = styled.p`
	font-family: 'Time new Roman';
	font-weight: 10;
	font-size: 40px;
`;

export default function Home(): JSX.Element {
	return (
		<div className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4" role="alert">
			{process.env.APP_NAME}
			<p className="font-bold">Yay, tailwind working</p>
			<Data>This p tag is generated by styled component.</Data>
		</div>
	);
}
